[package]
name = "missingnums"
version = "0.1.0"
authors = ["sseritan <sseritan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
